import { bigint, date, int, json, mysqlTable, varchar } from "drizzle-orm/mysql-core";
import { getDate } from "../../utils/utils";
// import { ModelTable } from "./Model";
// import { CategoryTable } from "./Grade";

export const EmployeeTable = mysqlTable('employee_table', {
    emp_id: int('emp_id').primaryKey().autoincrement(),
    map_id: int().notNull(),
    employee_id: varchar('employee_id', { length: 255 }),
    company_id: int('company_id').notNull(),
    employee_name: varchar('employee_name', { length: 255 }),
    nationality: varchar('nationality', { length: 255 }),
    country: varchar('country', { length: 255 }),
    organization: varchar('organization', { length: 255 }),
    division: varchar('division', { length: 255 }),
    section: varchar('section', { length: 255 }),
    join_date: varchar('join_date', { length: 255 }),
    business_unit: varchar('business_unit', { length: 255 }),
    department: varchar('department', { length: 255 }),
    job_title: varchar('job_title', { length: 255 }),
    grade: varchar('grade', { length: 255 }),
    cola: varchar('cola', { length: 255 }),
    basic_salary: varchar('basic_salary', { length: 255 }),
    housing_allowance: varchar('housing_allowance', { length: 255 }),
    transport_allowance: varchar('transport_allowance', { length: 255 }),
    utility_allowance: varchar('utility_allowance', { length: 255 }),
    uae_national_allowance: varchar('uae_national_allowance', { length: 255 }),
    supplementary_allowance: varchar('supplementary_allowance', { length: 255 }),
    consolidated_allowance: varchar('consolidated_allowance', { length: 255 }),
    gender: varchar("gender", { length: 255 }),
    other_allowance_1: varchar('other_allowance_1', { length: 255 }),
    other_allowance_2: varchar('other_allowance_2', { length: 255 }),
    other_allowance_3: varchar('other_allowance_3', { length: 255 }),
    other_allowance_4: varchar('other_allowance_4', { length: 255 }),
    total_fixed_allowance: varchar('total_fixed_allowance', { length: 255 }),
    total_fixed_cash: varchar('total_fixed_cash', { length: 255 })
});

// export const EmployeeDetailTable = mysqlTable('employee_detail_table', {
//     emp_id: int('emp_id').primaryKey().autoincrement(),
//     employee_id: varchar('employee_id', { length: 255 }),
//     company_id: int('company_id').notNull(),
//     employee_name: varchar('employee_name', { length: 255 }),
//     nationality: varchar('nationality', { length: 255 }),
//     country: varchar('country', { length: 255 }),
//     organization: varchar('organization', { length: 255 }),
//     division: varchar('division', { length: 255 }),
//     join_date: varchar('join_date', { length: 255 }),
//     section: varchar('section', { length: 255 }),
//     business_unit: varchar('business_unit', { length: 255 }),
//     department: varchar('department', { length: 255 }),
//     job_title: varchar('job_title', { length: 255 }),
//     grade: varchar('grade', { length: 255 }),
//     cola: varchar('cola', { length: 255 }),
//     basic_salary: varchar('basic_salary', { length: 255 }),
//     housing_allowance: varchar('housing', { length: 255 }),
//     transport_allowance: varchar('transport', { length: 255 }),
//     utility_allowance: varchar('utility', { length: 255 }),
//     uae_national_allowance: varchar('uae_national_allowance', { length: 255 }),
//     supplementary_allowance: varchar('supplementary', { length: 255 }),
//     gender: varchar("gender", { length: 255 }),
//     other_allowance_1: varchar('other_allowance_1', { length: 255 }),
//     other_allowance_2: varchar('other_allowance_2', { length: 255 }),
//     other_allowance_3: varchar('other_allowance_3', { length: 255 }),
//     other_allowance_4: varchar('other_allowance_4', { length: 255 }),
//     total_fixed_allowance: varchar('total_fixed_allowance', { length: 255 }),
//     total_fixed_cash: varchar('total_fixed_cash', { length: 255 }),
//     monthly_salary: json(),
//     current_yearly_salary: bigint({mode: "number"}),
//     new_yearly_salary: bigint({mode: "number"}),

//     model_id: int().references(() => ModelTable.model_id, { onDelete: "cascade" }).notNull(),
//     grade_number: varchar({ length: 255 }),
//     external_grade_number: varchar({ length: 255 }),
//     description: varchar({ length: 255 }),
//     category_id: int().references(() => CategoryTable.category_id, { onDelete: "cascade" }),

//     company: varchar({ length: 255 }),
//     sector: varchar({ length: 255 }),
//     role: varchar({ length: 255 }),
//     uae_national: varchar({ length: 255 }),
//     basic_min: varchar({ length: 255 }),
//     basic_mid: varchar({ length: 255 }),
//     basic_max: varchar({ length: 255 }),
//     total_allowance_min: varchar({ length: 255 }),
//     total_allowance_mid: varchar({ length: 255 }),
//     total_allowance_max: varchar({ length: 255 }),
//     total_fixed_min: varchar({ length: 255 }),
//     total_fixed_mid: varchar({ length: 255 }),
//     total_fixed_max: varchar({ length: 255 }),

//     last_modified: date().default(getDate()),
//     created_at: date().default(getDate()),
// });

export const EmployeeTableHistory = mysqlTable('employee_table_history', {
    emp_id: int('emp_id').primaryKey().autoincrement(),
    map_id: int().notNull(),
    employee_id: varchar('employee_id', { length: 255 }),
    company_id: int('company_id').notNull(),
    employee_name: varchar('employee_name', { length: 255 }),
    nationality: varchar('nationality', { length: 255 }),
    country: varchar('country', { length: 255 }),
    organization: varchar('organization', { length: 255 }),
    division: varchar('division', { length: 255 }),
    section: varchar('section', { length: 255 }),
    join_date: varchar('join_date', { length: 255 }),
    business_unit: varchar('business_unit', { length: 255 }),
    department: varchar('department', { length: 255 }),
    job_title: varchar('job_title', { length: 255 }),
    grade: varchar('grade', { length: 255 }),
    cola: varchar('cola', { length: 255 }),
    basic_salary: varchar('basic_salary', { length: 255 }),
    housing_allowance: varchar('housing_allowance', { length: 255 }),
    transport_allowance: varchar('transport_allowance', { length: 255 }),
    utility_allowance: varchar('utility_allowance', { length: 255 }),
    uae_national_allowance: varchar('uae_national_allowance', { length: 255 }),
    supplementary_allowance: varchar('supplementary_allowance', { length: 255 }),
    consolidated_allowance: varchar('consolidated_allowance', { length: 255 }),
    gender: varchar("gender", { length: 255 }),
    other_allowance_1: varchar('other_allowance_1', { length: 255 }),
    other_allowance_2: varchar('other_allowance_2', { length: 255 }),
    other_allowance_3: varchar('other_allowance_3', { length: 255 }),
    other_allowance_4: varchar('other_allowance_4', { length: 255 }),
    total_fixed_allowance: varchar('total_fixed_allowance', { length: 255 }),
    total_fixed_cash: varchar('total_fixed_cash', { length: 255 })
});